"""empty message

Revision ID: fdb6f4eb15af
Revises: cd1ea07af577
Create Date: 2024-08-15 20:43:29.954911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb6f4eb15af'
down_revision: Union[str, None] = 'cd1ea07af577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('building_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'department', 'building', ['building_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_column('department', 'building_id')
    # ### end Alembic commands ###
