"""empty message

Revision ID: 0af68108eb09
Revises: 5fa9e3b0bbe1
Create Date: 2024-08-15 23:22:27.977215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af68108eb09'
down_revision: Union[str, None] = '5fa9e3b0bbe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personnel2position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personnel2position')
    # ### end Alembic commands ###
