"""empty message

Revision ID: f85d51acff19
Revises: 8ea6dadc177e
Create Date: 2024-05-28 21:39:14.267970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85d51acff19'
down_revision: Union[str, None] = '8ea6dadc177e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corpus', sa.Column('profile', sa.String(length=200), nullable=True))
    op.add_column('corpus', sa.Column('year_release', sa.String(length=100), nullable=True))
    op.add_column('corpus', sa.Column('floors', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corpus', 'floors')
    op.drop_column('corpus', 'year_release')
    op.drop_column('corpus', 'profile')
    # ### end Alembic commands ###
