"""empty message

Revision ID: 5fa9e3b0bbe1
Revises: 89d483518ab8
Create Date: 2024-08-15 22:36:57.690799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa9e3b0bbe1'
down_revision: Union[str, None] = '89d483518ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('patient_patient_id_fkey', 'patient', type_='foreignkey')
    op.drop_column('patient', 'patient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('patient_patient_id_fkey', 'patient', 'patient', ['patient_id'], ['id'])
    # ### end Alembic commands ###
