"""empty message

Revision ID: 87431b3155d1
Revises: ad02fe1e0b8f
Create Date: 2024-07-19 21:43:48.908553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87431b3155d1'
down_revision: Union[str, None] = 'ad02fe1e0b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.String(), nullable=False),
    sa.Column('director', sa.String(), nullable=False),
    sa.Column('number_beds', sa.String(), nullable=False),
    sa.Column('staff', sa.String(), nullable=False),
    sa.Column('corpus', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
