"""empty message

Revision ID: cd1ea07af577
Revises: 0dc5219784bf
Create Date: 2024-08-13 23:17:30.432281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1ea07af577'
down_revision: Union[str, None] = '0dc5219784bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patient', 'doctor', ['doctor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient', type_='foreignkey')
    op.drop_column('patient', 'doctor_id')
    # ### end Alembic commands ###
