"""empty message

Revision ID: b5d32e367336
Revises: 84f3e590d125
Create Date: 2024-05-28 21:28:23.461547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d32e367336'
down_revision: Union[str, None] = '84f3e590d125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinic', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('clinic', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('corpus', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('corpus', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corpus', 'updated_at')
    op.drop_column('corpus', 'created_at')
    op.drop_column('clinic', 'updated_at')
    op.drop_column('clinic', 'created_at')
    # ### end Alembic commands ###
