from building.models import Building
from clinic.models import Clinic
from users.models import User
from doctors.models import Doctor
from department.models import Department
from patients.models import Patient
from hospital_room.models import HospitalRoom
from personnel.models import Personnel
from position.models import Position
