from building.models import *
from users.models import *
from clinic.models import *
from doctors.models import *
from department.models import *
from patients.models import *
from hospital_room.models import *
from personnel.models import *
from position.models import *